
POST http://localhost:4000/login 
Content-Type: application/json

{
    "username":"ghana",
    "password":"pana"
}

###

GET http://localhost:4000/home
Authorization : "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZ2hhbmEiLCJpYXQiOjE2MTk1NDAyMzUsImV4cCI6MTYxOTU0MDgzNX0.GVxS8HgwWNlSX-pMUv3vHBb2PTUFFC0cwn0hB7gyB1w" 

###

POST http://localhost:4000/checkotp 
Content-Type: application/json

{
    "username":"ghana",
    "otp":"142490",
    "emailId": "anirbandas0206@gmail.com"
}


###
GET http://localhost:4000/user/ongoing
Content-Type: application/json

{
    "username":"ghana"
}